### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by evilbuddy** [sazonische/csgo_models#10]
One of the recent game updates broke the plugin.
It makes a long time I didn't play the game, so I just deleted and recreated a server, reinstalled SM and MM, etc...
The server is working without this plugin.
When I have the plugin, the server crashes when I try to join it. I do not get any sourcemod logs or mdump file.

Thanks if you take the time to read and reply to this 😁

**Comment by sazonische** [comment]
https://github.com/sazonische/modelch/releases

**Comment by evilbuddy** [comment]
I updated modelch to the latest release, but nothing changed and the server still crashes when I join.
